module.exports=[
    {id:101,
    name:'Mothers y Combos',
    },
    {id:102,
    name:'Placa de video',
    },
    {id:103,
    name:'Accesorios',
    },
    {id:104,
    name:'Videos y juegos',
    },
    {id:105,
    name:'Equipos',
    },
    {id:106,
    name:'Pantallas',
    },
    {id:107,
    name:'Procesadores y coolers',
    },
    {id:108,
    name:'Gabinetes',
    },
    {id:109,
    name:'Almacenamiento',
    },
    {id:1010,
    name:'Memorias RAM',
    },
    {id:1011,
    name:'Perisfericos',
    },
    {id:1012,
    name:'Conectividad',
    },
    {id:1013,
    name:'Software',
    },
    {id:1014,
    name:'Oficina',
    }
]