module.exports=[
    {id:1,
    name:'Mothers y Combos',
    },
    {id:2,
    name:'Placa de video',
    },
    {id:3,
    name:'Accesorios',
    },
    {id:4,
    name:'Videos y juegos',
    },
    {id:5,
    name:'Equipos',
    },
    {id:6,
    name:'Pantallas',
    },
    {id:7,
    name:'Procesadores y coolers',
    },
    {id:8,
    name:'Gabinetes',
    },
    {id:9,
    name:'Almacenamiento',
    },
    {id:10,
    name:'Memorias RAM',
    },
    {id:11,
    name:'Perisfericos',
    },
    {id:12,
    name:'Conectividad',
    },
    {id:13,
    name:'Software',
    },
    {id:14,
    name:'Oficina',
    }
]