//USER
export const SET_USER = 'SET_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const FOUND_USER = 'FOUND_USER';
export const DESLOG_USER = 'DESLOG_USER';
export const FACEBOOK_USER = 'FACEBOOK_USER';

//Category
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_SINGLE_CATEGORY = 'RECEIVE_SINGLE_CATEGORY';

//SingleProduct
export const RECEIVE_SINGLE_PRODUCT = 'RECEIVE_SINGLE_PRODUCT';

//Loading
export const LOADING = 'LOADING';

//PRODUCTS
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';