//USER
export const SET_USER = 'SET_USER';

export const RECEIVE_USER = 'RECEIVE_USER';

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'

//SingleProduct
export const RECEIVE_SINGLE_PRODUCT = 'RECEIVE_SINGLE_PRODUCT';

//Loading
export const LOADING = 'LOADING';
//PRODUCTS
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';